### PR TITLE
added badges for travis and requires

### PR DESCRIPTION
**Pull request by eraymitrani**
resolving #25 but there is no .coveralls.yml file so I didn't add a badge for that one.

### CODE REVIEW

**Comment by rohithasrk** [comment]
@eraymitrani You can remove the badge headings too. Something like https://github.com/netjson/django-netjsongraph/blob/master/README.rst

**Comment by eraymitrani** [comment]
Is this better @rohithasrk ?

**Comment by rohithasrk** [comment]
@eraymitrani You can now add your name to CONTRIBUTORS.md. :smile:

**Comment by rohithasrk** [comment]
@eraymitrani There is no need of a coveralls.yml actually. We can call it directly from travis.yml itself. 
 Like this, https://github.com/IMGIITRoorkee/django-filemanager/blob/master/.travis.yml#L30. Just for your info. :smiley:

**Comment by eraymitrani** [comment]
Oh, good to know. Thanks 😃

**Pull request merged**
