### PR TITLE
Add right click menu on DOM

### PR DESCRIPTION
**Pull request by shaddygarg**

### CODE REVIEW

**Comment by shaddygarg** [comment]
#29

**Comment by shaddygarg** [comment]
This pull request closes #29

**Comment by rohithasrk** [comment]
@shaddygarg Can you check why there is a build error being thrown by Travis?

**Comment by shaddygarg** [comment]
I am looking into it.

**Comment by rohithasrk** [comment]
@shaddygarg #46 will fix it.

**Comment by shaddygarg** [comment]
Sure, @rohithasrk.

**Comment by shaddygarg** [comment]
There are maximum 50 folders allowed @rohithasrk. Seems like we need to work on it.

**Comment by rohithasrk** [comment]
Thank you @shaddygarg. You may add your name to CONTRIBUTORS.md now. :smile:

**Pull request merged**
